NAME=expander

include ../Makefile.master

download:
	if [ ! -e metamap.tgz ] ; then wget http://downloads.lappsgrid.org/deiis/metamap.tgz ; fi
	if [ ! -e pymetamap.tgz ] ; then wget http://downloads.lappsgrid.org/deiis/pymetamap.tgz ; fi
